### PR TITLE
update Delete.imageset to be PDF vector instead of PNG, similar to the other imagesets

### PR DESCRIPTION
**Pull request by clarkewd**
This fixes a build error on `macOS Catalina 10.15`:

    Build Failed
    Task failed with exit code 65:
    /usr/bin/xcrun xcodebuild -project /Users/me/loop/Carthage/Checkouts/LoopKit/LoopKit.xcodeproj -scheme LoopKitUI -configuration Release -derivedDataPath /Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/LoopKit/v2.2.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/6w/8jqg16211dx54wpklq0yr57m0000gn/T/LoopKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/me/loop/Carthage/Checkouts/LoopKit)

Looks like the `actool` doesn't like the `PNG` version of the images in the `Delete.imageset` subfolder of the assets. The other folders have `PDF` versions so I've updated this one to be the same.

The build log has further details:

    CompileAssetCatalog /Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/LoopKit/v2.2.2/Build/Intermediates.noindex/ArchiveIntermediates/LoopKitUI/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/LoopKitUI.framework /Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets (in target 'LoopKitUI' from project 'LoopKit')
        cd /Users/me/loop/Carthage/Checkouts/LoopKit
        /Applications/Xcode.app/Contents/Developer/usr/bin/actool --output-format human-readable-text --notices --warnings --export-dependency-info /Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/LoopKit/v2.2.2/Build/Intermediates.noindex/ArchiveIntermediates/LoopKitUI/IntermediateBuildFilesPath/LoopKit.build/Release-iphoneos/LoopKitUI.build/assetcatalog_dependencies --output-partial-info-plist /Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/LoopKit/v2.2.2/Build/Intermediates.noindex/ArchiveIntermediates/LoopKitUI/IntermediateBuildFilesPath/LoopKit.build/Release-iphoneos/LoopKitUI.build/assetcatalog_generated_info.plist --compress-pngs --enable-on-demand-resources NO --sticker-pack-identifier-prefix com.loopkit.LoopKitUI.sticker-pack. --development-region English --target-device iphone --target-device ipad --minimum-deployment-target 11.1 --platform iphoneos --product-type com.apple.product-type.framework --compile /Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/LoopKit/v2.2.2/Build/Intermediates.noindex/ArchiveIntermediates/LoopKitUI/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/LoopKitUI.framework /Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets
    ibtoold[26460:554598] DEBUG: Added to environment: {
        TMPDIR = "/var/folders/6w/8000001020101028481aad9f912919/T/3928830E-D290-4CDC-9D5D-281737819231";
    }
    IBCocoaTouchImageCatalogTool[26476:555638] Unable to get image dimensions for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@2x.png
    IBCocoaTouchImageCatalogTool[26476:555638] Unable to get image dimensions for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@3x.png
    IBCocoaTouchImageCatalogTool[26476:555638] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@3x.png
    IBCocoaTouchImageCatalogTool[26476:555638] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@2x.png
    IBCocoaTouchImageCatalogTool[26476:555638] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@2x.png
    IBCocoaTouchImageCatalogTool[26476:555638] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@3x.png
    IBCocoaTouchImageCatalogTool[26476:555638] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@3x.png
    IBCocoaTouchImageCatalogTool[26476:555638] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@2x.png
    IBCocoaTouchImageCatalogTool[26476:555638] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@2x.png
    IBCocoaTouchImageCatalogTool[26476:555638] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@2x.png
    IBCocoaTouchImageCatalogTool[26476:555638] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@3x.png
    IBCocoaTouchImageCatalogTool[26476:555638] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@3x.png
    IBCocoaTouchImageCatalogTool[26476:555638] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@3x.png
    IBCocoaTouchImageCatalogTool[26476:555638] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@2x.png
    IBCocoaTouchImageCatalogTool[26476:555705] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@3x.png
    IBCocoaTouchImageCatalogTool[26476:555731] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@2x.png
    IBCocoaTouchImageCatalogTool[26476:555738] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@3x.png
    IBCocoaTouchImageCatalogTool[26476:555731] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@2x.png
    IBCocoaTouchImageCatalogTool[26476:555734] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@3x.png
    IBCocoaTouchImageCatalogTool[26476:555737] CoreThemeDefinition: Unable to create image for file:///Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets/Delete.imageset/Delete@2x.png
    /* com.apple.actool.errors */
    /Users/me/loop/Carthage/Checkouts/LoopKit/LoopKitUI/Assets.xcassets: error: Distill failed for unknown reasons.

### CODE REVIEW

**Comment by clarkewd** [comment]
This is a pretty simple pull request - just updating an image resource to use vector. Would you mind taking a look and accepting it, if it seems ok? Thanks! :)

**Comment by ps2** [comment]
What Xcode version are you using? I am not seeing this error building on Catalina and Xcode 11.1.

**Comment by clarkewd** [comment]
Thanks Pete. Yes, I have the same - Catalina and Xcode 11.1

Since the checks pass, and the other imagesets are using PDF versions, can we also update this one?

**Comment by ps2** [comment]
This patch is against master, please test against dark mode, as well.

**Comment by ps2** [comment]
Closing; this is not fixing any issue, and is against master.

**Pull request closed without merging**
