### PR TITLE
HKUnit extension no longer needs to be public.

### PR DESCRIPTION
**Pull request by bharat**
Now that .milligramsPerDeciliterUnit is replicated in Loop.

### CODE REVIEW

**Comment by ps2** [comment]
/Users/travis/build/LoopKit/LoopKit/CarbKit/CarbMath.swift:79:64: error: 'milligramsPerDeciliterUnit' is inaccessible due to 'internal' protection level
            value = insulinSensitivity.doubleValue(for: HKUnit.milligramsPerDeciliterUnit()) / carbRatio.doubleValue(for: unit) * absorbedCarbs(entry.quantity.doubleValue(for: unit), atTime: time - delay, absorptionTime: entry.absorptionTime ?? defaultAbsorptionTime)
                                                               ^
<unknown>:0: note: 'milligramsPerDeciliterUnit' declared here
/Users/travis/build/LoopKit/LoopKit/CarbKit/CarbMath.swift:149:27: error: 'milligramsPerDeciliterUnit' is inaccessible due to 'internal' protection level
        let unit = HKUnit.milligramsPerDeciliterUnit()
                          ^
<unknown>:0: note: 'milligramsPerDeciliterUnit' declared here

**Comment by ps2** [comment]
I think if this is rebased it may pass tests now...

**Comment by bharat** [comment]
I merged the latest upstream/dev, but haven't had a chance to dig into the failures. will wait to see what Travis says...

**Comment by ps2** [comment]
The logs show 
```
/Users/travis/build/LoopKit/LoopKit/GlucoseKitTests/GlucoseMathTests.swift:39:44: error: ambiguous use of 'milligramsPerDeciliterUnit()'
                quantity: HKQuantity(unit: HKUnit.milligramsPerDeciliterUnit(), doubleValue: $0["amount"] as! Double),
```

**Comment by ps2** [comment]
This was addressed in #127

**Pull request closed without merging**
