### PR TITLE
Add warning if carb quantity exceeds warning limit

### PR DESCRIPTION
**Pull request by marionbarker**
One of two PR (see also Loop) in response to Feature Request https://github.com/LoopKit/Loop/issues/1862

### CODE REVIEW

**Comment by marionbarker** [comment]
<details>
  <summary>Obviated screenshots</summary>
  
The new modal screen for the warning (shown only once for a given quantity), updated for most recent commit:

IMG_0294
</details>

**Comment by marionbarker** [comment]
<details>
  <summary>Obviated screenshots</summary>
  
The modified max quantity screen, title and message were changed.
Updated for most recent commit.

IMG_0293
</details>

**Comment by ps2** [comment]
Copy suggestions:

1) On the over limit dialog
 * Title: "Unacceptable Entry" -> "Input Maximum Exceeded" (more specific and less judgmental connotation)
 * Message: "The maximum allowed amount is 250 grams, edit or cancel entry."  Run on sentence. Either drop the "edit or cancel entry" or add a new sentence offering suggestions on what to do. Not sure that's needed, but maybe "Please reduce the amount entered."  Suggesting cancel is probably not needed here; they likely *are* trying to enter a meal, and if they decide not to, the cancel button is very visible.

2) On the warning dialog:
 * Title: "Entry Warning". Should say something about what happened. Like "Large Meal Entered"
 * Message: "Please double check your entered amount to make sure it's correct." 
 * Options: "It's Correct", or "Edit Amount".

**Comment by marionbarker** [comment]
Suggestion incorporated and graphics (prior comments) were updated.

**Comment by ps2** [comment]
Updated with two actions: 
Screen Shot 2022-12-18 at 12 24 29 PM

**Comment by ps2** [comment]
Screen Shot 2022-12-18 at 12 40 16 PM

**Pull request merged**
