### PR TITLE
Increase upper range of recommendedBounds

### PR DESCRIPTION
**Pull request by marionbarker**
Increase upper range of recommendedBounds for suspendThreshold and correctionRange.

This provides support to new Loopers who may wish to start at higher levels than is typical.

The overall ranges (absoluteBounds) are not modified.

### CODE REVIEW

**Comment by ps2** [comment]
This needs to be done in a code-configurable way, as Tidepool can't take these changes easily.

**Comment by marionbarker** [comment]
Happy to make changes but I’m not sure how you want it changed. Do you mean create (or use an existing) config file to hold the values?

**Comment by ps2** [comment]
The ideal solution for this is 1) have these values not specified in LoopKit, but allow Loop to control them. 2) Be able to override the default Loop values at build time, preferably via something like xcconfig (LoopConfigOverride), so custom guardrails could be specified at a higher level. But xcconfig isn't great for specifying more complex types, so I'm not quite sure what the best solution here is. We definitely need build time config.

**Comment by ps2** [comment]
Closing this PR. Not opposed to allowing a higher range, but there is a lot more to supporting that than what's submitted in this PR. Graphic in therapy settings also affected.

**Pull request closed without merging**
