### PR TITLE
Updated food emojis

### PR DESCRIPTION
**Pull request by diggabyte**
Added some missing emojis (🧃, 🍩, 🥬, 🫐, 🍴, 🍽, 🥄, 😋), cleaned up file structure, added comments for each emoji for readability.

Also moved a number of high-sugar content items like ice cream, cookie, shortcake & chocolate ( 🍨, 🍪, 🍰, 🍫)  into **fast**  and out of **medium**.

### CODE REVIEW

**Comment by ps2** [comment]
You re-categorized things (like moving chocolate from medium to fast) that were already carefully placed. See the [emoji doc](https://docs.google.com/spreadsheets/d/1-Lfyi69K7frsWnjcY-j-35wguG00y5azVEG9VY1zba4/edit#gid=0).  This will be a lot easier to accept if you just add missing emojis, rather than reworking many things.

**Comment by ps2** [comment]
30 minute absorption is *really* fast, and even many foods that have a lot of sugar in them will not absorb that fast, if they're mixed with other fats or protein, like ice cream, chocolate bars, etc..

**Comment by diggabyte** [comment]
@ps2 gotcha, I was wondering about that. Thanks, I'll reference the doc and update accordingly.

**Comment by ps2** [comment]
And reformatting at the same time as adding, makes it hard for me to see which things are additions. Please either note the additions, or do the work in two steps (simple reformat that I can just merge and then additions that I can review).

**Comment by diggabyte** [comment]
No problem, I'll make two MRs -- one for formatting, one for additions.

**Comment by diggabyte** [comment]
Closing this in favor of two distinct MRs for clarity

**Comment by diggabyte** [comment]
@ps2 here's the formatting-only changes first: https://github.com/LoopKit/LoopKit/pull/457

**Comment by diggabyte** [comment]
@ps2 here's the additions https://github.com/LoopKit/LoopKit/pull/458

**Pull request closed without merging**
